# Generated by Django 5.0.6 on 2024-07-05 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='uploading_date',
        ),
        migrations.AddField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
